### ISSUE TITLE
Successfully executing the visualize.py code nothing is saved in the folder.

### ISSUE THREAD

**Issue by G-raghava** [kbrodt/waymo-motion-prediction-2021#18]
Hi, Today also facing the same issue. can someone help me is there any process to do it.

![image](https://user-images.githubusercontent.com/92630358/235318025-c2926d97-1ad3-4f2e-af9b-d085985d5fe8.png)

whatever the path is given for saving the folder it exists but the file is saved in the folder.

"/home/talapallysk/waymo-motion-prediction-2021/viz/xception71/" I have provided the path for the folder saved but no file is saved. Please help me

**Comment by Leon77zusammen** [comment]
have you solved this problem? I have found the same problem with you . No visuaized plot or files are saved in the folder.
 @kbrodt do you have any ideas? Can u share your model_best.pt with us? I think it might be a problem with the model. Tks~
@asanakoy @stepankonev Also thank you both. 


comment edit after 1 hour :)
I have looked through the visualize code, and found that the DataLoader(WaymoLoader) should load the processed batch data, not the raw data. So the args --data ${DATA_PATH} should be ./dev ./train ./test. 

The Problem is solved.@G-raghava
